"""
HBS Faculty Enrichment Scraper
===============================
Fetches rich profile data (bio, title, email, photo) and recent
publications from HBS faculty profile pages.

Faculty list is loaded dynamically from scripts/all_faculty.json
(generated by scrape_faculty_directory.py). Run that script first.

Must be run locally -- hbs.edu returns 403 to server-side / cloud requests.
Uses Playwright (headless Chromium) so that JavaScript-rendered content
is fully loaded before parsing.

Photos are derived directly from the predictable HBS headshot API URL
(no scraping needed): Style Library/api/headshot.aspx?id={facId}

Research keyword tags are managed via the curated migration seed
(008_seed_faculty_tags.sql) and are not scraped here.

Usage:
    cd scripts
    python scrape_faculty_directory.py   # produces all_faculty.json first
    python hbs_scraper.py

Output: scripts/enriched_faculty.json
"""

import json
import re
import time
from pathlib import Path

from bs4 import BeautifulSoup
from playwright.sync_api import sync_playwright

# ── Configuration ─────────────────────────────────────────────────────────────

OUTPUT_FILE       = Path(__file__).parent / "enriched_faculty.json"
ALL_FACULTY_FILE  = Path(__file__).parent / "all_faculty.json"
DEBUG_HTML        = Path(__file__).parent / "debug_profile.html"  # saved when DEBUG=True
DEBUG             = False  # set True to save the first profile's HTML for inspection
START_FROM        = 0     # set to N to skip the first N faculty (useful for resuming)

# ── Faculty list ──────────────────────────────────────────────────────────────

def load_faculty() -> list[tuple[str, str]]:
    """
    Load the full faculty list from all_faculty.json.
    Returns a list of (hbs_fac_id, name) tuples.
    Run scrape_faculty_directory.py first to generate this file.
    """
    if not ALL_FACULTY_FILE.exists():
        raise FileNotFoundError(
            f"{ALL_FACULTY_FILE} not found.\n"
            "Run: python scrape_faculty_directory.py"
        )
    with open(ALL_FACULTY_FILE, encoding="utf-8") as f:
        data = json.load(f)
    return [(row["hbs_fac_id"], row["name"]) for row in data if row.get("hbs_fac_id")]


PROFILE_BASE  = "https://www.hbs.edu/faculty/Pages/profile.aspx?facId={}&view=publications"
# HBS headshot API — returns a JPEG for any valid facId
HEADSHOT_BASE = "https://www.hbs.edu/Style%20Library/api/headshot.aspx?id={}"

# Publication section heading text -> pub_type mapping
# HBS uses ALL-CAPS headings like "JOURNAL ARTICLES", "WORKING PAPERS", etc.
PUB_SECTION_TYPES = {
    "journal article": "Journal Article",
    "article":         "Journal Article",
    "book chapter":    "Chapter",
    "chapter":         "Chapter",
    "book":            "Book",
    "case":            "Case",
    "working paper":   "Working Paper",
    "conference":      "Conference Paper",
    "report":          "Report",
    "other":           "Other",
}

YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")

MAX_PUBLICATIONS = 25          # total cap per faculty
TYPE_QUOTAS = {                # guaranteed minimums (where available)
    "Journal Article": 5,
    "Working Paper":   5,
    "Case":            5,
    "Book":            3,      # books are rarer; include all if ≤3, else most recent 3
}


# ── Fetch helpers ─────────────────────────────────────────────────────────────

def fetch_profile(page, fac_id: str, save_debug: bool = False):
    """Navigate to a faculty profile page and return fully-rendered HTML as BeautifulSoup."""
    url = PROFILE_BASE.format(fac_id)
    try:
        page.goto(url, wait_until="domcontentloaded", timeout=20000)
        # Give JS a moment to render publication containers
        page.wait_for_timeout(2000)
        html = page.content()
        if save_debug:
            DEBUG_HTML.write_text(html, encoding="utf-8")
            print(f"    [debug] Saved rendered HTML to {DEBUG_HTML}")
        return BeautifulSoup(html, "lxml")
    except Exception as e:
        print(f"    X Error loading facId={fac_id}: {e}")
        return None


# ── Photo ─────────────────────────────────────────────────────────────────────

def get_photo_url(fac_id: str) -> str:
    """
    Return the HBS headshot API URL for this faculty member.
    The URL is predictable — no scraping required.
    """
    return HEADSHOT_BASE.format(fac_id)


# ── Profile detail scraping ───────────────────────────────────────────────────

def scrape_profile_details(soup) -> dict:
    """
    Extract bio, title, unit, and email from a fully-rendered HBS faculty profile page.

    Returns a dict with keys: title, bio, email, unit (each str or None).
    """
    title = _scrape_title(soup)
    bio   = _scrape_bio(soup)
    email = _scrape_email(soup)
    unit  = _scrape_unit(soup)
    return {"title": title, "bio": bio, "email": email, "unit": unit}


def _scrape_title(soup) -> str | None:
    """
    Faculty title/rank (e.g. "Baker Foundation Professor of Business Administration").
    HBS renders this in an <h2 class="... subtitle ..."> element in the profile header.
    """
    # Primary: h2 with class "subtitle" (confirmed from HBS profile HTML)
    for h2 in soup.find_all("h2", class_="subtitle"):
        text = h2.get_text(strip=True)
        if text and 3 < len(text) < 150:
            return text

    # Fallback: any h2/h3 whose text looks like a professorship
    TITLE_RE = re.compile(r'\bProfessor\b', re.I)
    for tag in soup.find_all(["h2", "h3"]):
        classes = " ".join(tag.get("class", []))
        if re.search(r"toggle|nav|menu|footer|breadcrumb", classes, re.I):
            continue
        text = tag.get_text(strip=True)
        if 5 < len(text) < 150 and TITLE_RE.search(text):
            return text

    return None


def _scrape_bio(soup) -> str | None:
    """
    Faculty biography text.
    HBS profiles have a bio section — try common class patterns.
    """
    # Try class-based selectors
    candidates = [
        soup.find(class_=re.compile(r"biography|bio|about", re.I)),
        soup.find("div", class_=re.compile(r"faculty.content|profile.content", re.I)),
        soup.find("section", class_=re.compile(r"bio|about", re.I)),
    ]
    for el in candidates:
        if el:
            # Prefer paragraph text only — HBS heading elements repeat name/title
            paras = el.find_all("p")
            if paras:
                text = " ".join(p.get_text(separator=" ", strip=True) for p in paras)
            else:
                text = el.get_text(separator=" ", strip=True)
            # Bio should be substantial — at least 80 chars
            if text and len(text) >= 80:
                return _clean_bio(text)

    # Fallback: look for the largest <p>-containing div that isn't in a pub section
    pub_containers = soup.find_all("div", class_="toggle-container")
    pub_texts = {c.get_text()[:50] for c in pub_containers}

    for div in soup.find_all("div"):
        classes = " ".join(div.get("class", []))
        if re.search(r"nav|menu|footer|header|sidebar|toggle|breadcrumb", classes, re.I):
            continue
        text = div.get_text(separator=" ", strip=True)
        if text[:50] in pub_texts:
            continue
        if 200 <= len(text) <= 3000:
            # Check it has sentence-like content (ends with punctuation)
            if re.search(r"[.!?]\s", text):
                return _clean_bio(text)

    return None


def _clean_bio(text: str) -> str:
    """Strip scraping artifacts (e.g. 'Read more' buttons) from bio text."""
    # Remove "Read more" and anything after it (HBS website expand-button text)
    text = re.sub(r"\s*\bRead more\b.*$", "", text, flags=re.I | re.DOTALL)
    return text.strip()[:4000]


def _scrape_unit(soup) -> str | None:
    """
    Extract the faculty member's academic unit from their profile page.
    HBS uses 10 canonical unit names. The unit typically appears as a
    link in the breadcrumb or sidebar — check link text first, then
    fall back to full page text (handles &amp; encoding differences).
    """
    CANONICAL_UNITS = [
        "Accounting & Management",
        "Business, Government & International Economy",
        "Entrepreneurial Management",
        "Finance",
        "General Management",
        "Marketing",
        "Negotiation, Organizations & Markets",
        "Organizational Behavior",
        "Strategy",
        "Technology & Operations Management",
    ]

    # Strategy 1: check all link text (unit is usually a clickable link)
    for a in soup.find_all("a"):
        text = a.get_text(strip=True)
        for unit in CANONICAL_UNITS:
            if unit.lower() == text.lower():
                return unit

    # Strategy 2: substring match in full page text
    # get_text() decodes &amp; → & so this handles HTML entity differences
    page_text = soup.get_text()
    for unit in CANONICAL_UNITS:
        if unit in page_text:
            return unit

    # Strategy 3: partial keyword match as last resort
    UNIT_KEYWORDS = {
        "Accounting":        "Accounting & Management",
        "Business, Government": "Business, Government & International Economy",
        "Entrepreneurial":   "Entrepreneurial Management",
        "Finance":           "Finance",
        "General Management": "General Management",
        "Marketing":         "Marketing",
        "Negotiation":       "Negotiation, Organizations & Markets",
        "Organizational Behavior": "Organizational Behavior",
        "Strategy":          "Strategy",
        "Technology & Operations": "Technology & Operations Management",
    }
    for keyword, unit in UNIT_KEYWORDS.items():
        if keyword in page_text:
            return unit

    return None


def _scrape_email(soup) -> str | None:
    """Extract first mailto: link from the page."""
    a = soup.find("a", href=re.compile(r"^mailto:", re.I))
    if a:
        href = a.get("href", "")
        email = href[len("mailto:"):].split("?")[0].strip()
        if "@" in email:
            return email
    return None



# ── Publication scraping ──────────────────────────────────────────────────────

def scrape_publications(soup, fac_id: str) -> list:
    """
    Extract recent publications from a fully-rendered HBS faculty profile page.

    HBS page structure:
      <div class="toggle-container">
        <h3 class="eta-uc">
          <div class="toggle-hide"><a>JOURNAL ARTICLES</a></div>
        </h3>
        <div class="toggle-hide has-slide">
          <ul class="unstyled list-publications ...">
            <li><div>Authors. <a href="...">Title</a> Journal Year. <a>View Details</a></div></li>
            ...
          </ul>
        </div>
      </div>
    """
    pubs = []

    for container in soup.find_all("div", class_="toggle-container"):
        h3 = container.find("h3")
        if not h3:
            continue

        heading_text = h3.get_text(strip=True).lower()
        # Normalise plural: "journal articles" -> match "journal article"
        heading_text = heading_text.rstrip("s")

        pub_type = None
        for pattern, ptype in PUB_SECTION_TYPES.items():
            if pattern in heading_text:
                pub_type = ptype
                break
        if pub_type is None:
            continue

        pub_list = container.find("ul", class_=re.compile(r"list-publication", re.I))
        if not pub_list:
            # Fallback: any ul within the container
            pub_list = container.find("ul")
        if not pub_list:
            continue

        for li in pub_list.find_all("li", recursive=False):
            pub = _parse_pub_entry(li, pub_type)
            if pub:
                pubs.append(pub)

    pubs = _dedup_pubs(pubs)
    return _select_with_quotas(pubs)


def _select_with_quotas(pubs: list) -> list:
    """
    Select up to MAX_PUBLICATIONS publications using a quota-then-fill strategy:
      1. Guarantee up to TYPE_QUOTAS[type] most-recent pubs per priority type.
      2. Fill any remaining slots (up to MAX_PUBLICATIONS) with the most recent
         publications across all types not yet included.
      3. Return sorted by year descending.
    """
    # Sort all pubs by year desc once
    by_year = sorted(pubs, key=lambda p: p.get("year") or 0, reverse=True)

    selected = []
    seen = set()  # keyed by lowercased title prefix

    def _add(pub):
        key = pub["title"].lower()[:80]
        if key not in seen:
            seen.add(key)
            selected.append(pub)

    # Step 1 — fill guaranteed slots per priority type (most recent first)
    by_type = {}
    for pub in by_year:
        by_type.setdefault(pub["pub_type"], []).append(pub)

    for pub_type, quota in TYPE_QUOTAS.items():
        for pub in by_type.get(pub_type, [])[:quota]:
            _add(pub)

    # Step 2 — fill remaining slots with most-recent across all types
    for pub in by_year:
        if len(selected) >= MAX_PUBLICATIONS:
            break
        _add(pub)

    # Step 3 — return sorted by year desc
    selected.sort(key=lambda p: p.get("year") or 0, reverse=True)
    return selected


def _parse_pub_entry(entry, pub_type: str):
    """
    Parse a single <li> publication entry.

    HBS entry structure:
      <li>
        <div>Authors. <a href="URL">Title text <span class="pdf-append">(pdf)</span></a>
             <i>Journal Name</i> Vol (Year): pages. <a>View Details</a></div>
        <div class="shim20"></div>
      </li>
    """
    text = entry.get_text(separator=" ", strip=True)
    if len(text) < 10:
        return None

    # Find the first <a> that is NOT a "View Details" / toggle link
    title_tag = None
    url = None
    view_details_url = None
    for a in entry.find_all("a"):
        a_text = a.get_text(strip=True)
        href = a.get("href", "")
        if a_text.lower() in ("view details", "view detail", "") or href.startswith("#"):
            # Capture View Details URL as fallback for case entries
            if a_text.lower().startswith("view detail") and href and not href.startswith("#"):
                view_details_url = href if href.startswith("http") else "https://www.hbs.edu" + href
            continue
        title_tag = a
        if href and not href.startswith("#"):
            url = href if href.startswith("http") else "https://www.hbs.edu" + href
        break
    # Use View Details URL when there's no primary link (common for cases)
    if not url and view_details_url:
        url = view_details_url

    if title_tag:
        # Get title text, strip surrounding quotes and the "(pdf)" suffix
        raw_title = title_tag.get_text(strip=True)
        raw_title = re.sub(r"\s*\(pdf\)\s*$", "", raw_title, flags=re.I).strip()
        title = raw_title.strip('"').strip("\u201c\u201d").strip("'").strip()
    else:
        # No title link — title is in the plain text, usually in quotes.
        # e.g. 'Smith, J. "Case Title." HBS Case 123-456, 2024. View Details'
        quoted = re.search(r'["\u201c\u201e]([^"\u201c\u201d\u201e]{10,})["\u201d]', text)
        if quoted:
            title = quoted.group(1).strip().rstrip(".")
        else:
            # Last resort: use the italicised text if present
            italic = entry.find("i")
            title = italic.get_text(strip=True) if italic else ""

    if not title or len(title) < 5:
        return None

    # Year: first 4-digit year in the full text
    year_match = YEAR_RE.search(text)
    year = int(year_match.group()) if year_match else None

    # Journal: look for <i> tag (HBS italicises journal names)
    journal = None
    italic = entry.find("i")
    if italic:
        journal_text = italic.get_text(strip=True)
        if journal_text and len(journal_text) < 120:
            journal = journal_text

    return {"title": title, "year": year, "pub_type": pub_type, "journal": journal, "url": url}


def _dedup_pubs(pubs: list) -> list:
    seen = set()
    result = []
    for pub in pubs:
        key = pub["title"].lower()[:80]
        if key not in seen:
            seen.add(key)
            result.append(pub)
    return result


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    faculty_list = load_faculty()

    if START_FROM:
        faculty_list = faculty_list[START_FROM:]

    print("HBS Faculty Enrichment Scraper (Playwright)")
    print("=" * 50)
    print(f"Scraping {len(faculty_list)} faculty members"
          + (f" (starting from #{START_FROM + 1})" if START_FROM else "") + "...\n")

    results = []

    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled"],
        )

        CONTEXT_RESTART_EVERY = 10  # fresh context every N faculty to avoid memory/throttle issues

        def make_context():
            ctx = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/124.0.0.0 Safari/537.36"
                ),
                locale="en-US",
                viewport={"width": 1280, "height": 800},
            )
            ctx.add_init_script(
                "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
            )
            return ctx

        context = make_context()

        for i, (fac_id, name) in enumerate(faculty_list, 1):
            # Restart context periodically to clear memory and refresh connection
            if i > 1 and (i - 1) % CONTEXT_RESTART_EVERY == 0:
                context.close()
                print(f"\n  [restarting browser context after {i - 1} faculty]\n")
                time.sleep(3)
                context = make_context()

            print(f"[{i:3}/{len(faculty_list)}] {name} (facId={fac_id})")

            page = context.new_page()
            soup = fetch_profile(page, fac_id, save_debug=(DEBUG and i == 1))
            page.close()

            photo_url    = get_photo_url(fac_id)
            publications = scrape_publications(soup, fac_id) if soup else []
            details      = scrape_profile_details(soup) if soup else {}

            type_counts = {}
            for p in publications:
                type_counts[p["pub_type"]] = type_counts.get(p["pub_type"], 0) + 1
            breakdown = ", ".join(f"{v} {k}" for k, v in sorted(type_counts.items()))
            has_bio   = "✓" if details.get("bio") else "–"
            has_email = "✓" if details.get("email") else "–"
            has_title = "✓" if details.get("title") else "–"
            has_unit  = "✓" if details.get("unit") else "–"
            print(f"           pubs: {len(publications)} ({breakdown})")
            print(f"           bio:{has_bio}  email:{has_email}  title:{has_title}  unit:{has_unit}")

            results.append({
                "hbs_fac_id":   fac_id,
                "photo_url":    photo_url,
                "title":        details.get("title"),
                "bio":          details.get("bio"),
                "email":        details.get("email"),
                "unit":         details.get("unit"),
                "tags":         [],   # managed via curated migration seed
                "publications": publications,
            })

            time.sleep(2)  # slightly longer pause to reduce server-side throttling

        context.close()
        browser.close()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    total_pubs   = sum(len(r["publications"]) for r in results)
    total_photos = sum(1 for r in results if r.get("photo_url"))
    total_bios   = sum(1 for r in results if r.get("bio"))
    total_emails = sum(1 for r in results if r.get("email"))
    total_titles = sum(1 for r in results if r.get("title"))
    total_units  = sum(1 for r in results if r.get("unit"))

    print("\n" + "=" * 50)
    print("Done!")
    print(f"   Photos (URL):         {total_photos}")
    print(f"   Bios scraped:         {total_bios}")
    print(f"   Titles scraped:       {total_titles}")
    print(f"   Units scraped:        {total_units}")
    print(f"   Emails scraped:       {total_emails}")
    print(f"   Publications scraped: {total_pubs}")
    print(f"   Output: {OUTPUT_FILE}")
    print()
    print("Next step: node scripts/import-enriched.mjs")


if __name__ == "__main__":
    main()
