"""
HBS Faculty Enrichment Scraper
===============================
Fetches rich profile data (bio, title, email, photo) and recent
publications from HBS faculty profile pages.

Faculty list is loaded dynamically from scripts/all_faculty.json
(generated by scrape_faculty_directory.py). Run that script first.

Must be run locally -- hbs.edu returns 403 to server-side / cloud requests.
Uses Playwright (headless Chromium) so that JavaScript-rendered content
is fully loaded before parsing.

Photos are derived directly from the predictable HBS headshot API URL
(no scraping needed): Style Library/api/headshot.aspx?id={facId}

Research keyword tags are managed via the curated migration seed
(008_seed_faculty_tags.sql) and are not scraped here.

Usage:
    cd scripts
    python scrape_faculty_directory.py   # produces all_faculty.json first
    python hbs_scraper.py

Output: scripts/enriched_faculty.json
"""

import json
import random
import re
import time
from pathlib import Path

from bs4 import BeautifulSoup
from playwright.sync_api import sync_playwright

try:
    from playwright_stealth import Stealth as _Stealth
    _STEALTH = _Stealth()
    _HAS_STEALTH = True
except ImportError:
    _HAS_STEALTH = False

# ── Configuration ─────────────────────────────────────────────────────────────

OUTPUT_FILE       = Path(__file__).parent / "enriched_faculty.json"
ALL_FACULTY_FILE  = Path(__file__).parent / "all_faculty.json"
DEBUG_HTML        = Path(__file__).parent / "debug_profile.html"  # saved when DEBUG=True
DEBUG             = False  # set True to save the first profile's HTML for inspection
START_FROM        = 0     # set to N to skip the first N faculty (useful for resuming)
HEADLESS          = False  # False = real visible browser; much harder for Cloudflare to block

# When non-empty, only scrape these hbs_fac_ids and write to a separate output file.
# Leave empty (set()) to run the full faculty list.
FILTER_IDS: set[str] = set()

# ── Faculty list ──────────────────────────────────────────────────────────────

def load_faculty() -> list[tuple[str, str]]:
    """
    Load the full faculty list from all_faculty.json.
    Returns a list of (hbs_fac_id, name) tuples.
    Run scrape_faculty_directory.py first to generate this file.
    """
    if not ALL_FACULTY_FILE.exists():
        raise FileNotFoundError(
            f"{ALL_FACULTY_FILE} not found.\n"
            "Run: python scrape_faculty_directory.py"
        )
    with open(ALL_FACULTY_FILE, encoding="utf-8") as f:
        data = json.load(f)
    return [(row["hbs_fac_id"], row["name"]) for row in data if row.get("hbs_fac_id")]


PROFILE_BASE  = "https://www.hbs.edu/faculty/Pages/profile.aspx?facId={}&view=publications"
# HBS headshot API — returns a JPEG for any valid facId
HEADSHOT_BASE = "https://www.hbs.edu/Style%20Library/api/headshot.aspx?id={}"

# Publication section heading text -> pub_type mapping
# HBS uses ALL-CAPS headings like "JOURNAL ARTICLES", "WORKING PAPERS", etc.
PUB_SECTION_TYPES = {
    "journal article": "Journal Article",
    "article":         "Journal Article",
    "book chapter":    "Chapter",
    "chapter":         "Chapter",
    "book":            "Book",
    "case":            "Case",
    "working paper":   "Working Paper",
    "conference":      "Conference Paper",
    "report":          "Report",
    "other":           "Other",
}

YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")

MAX_PUBLICATIONS = 25          # total cap per faculty
TYPE_QUOTAS = {                # guaranteed minimums (where available)
    "Journal Article": 5,
    "Working Paper":   5,
    "Case":            5,
    "Book":            3,      # books are rarer; include all if ≤3, else most recent 3
}


# ── Fetch helpers ─────────────────────────────────────────────────────────────

_CAPTCHA_SIGNALS = [
    "solve a puzzle",
    "cf-browser-verification",
    "Checking your browser",
    "DDoS protection by",
    "Please wait while we verify",
    "cf_chl_opt",
]


def _is_captcha_page(html: str) -> bool:
    """Return True if the rendered page is a bot-challenge / CAPTCHA page."""
    return any(signal.lower() in html.lower() for signal in _CAPTCHA_SIGNALS)


def fetch_profile(page, fac_id: str, save_debug: bool = False):
    """Navigate to a faculty profile page and return fully-rendered HTML as BeautifulSoup."""
    url = PROFILE_BASE.format(fac_id)
    try:
        page.goto(url, wait_until="domcontentloaded", timeout=20000)
        # Give JS a moment to render publication containers
        page.wait_for_timeout(2000)
        html = page.content()
        if _is_captcha_page(html):
            print(f"    ⚠ CAPTCHA detected for facId={fac_id} — skipping")
            return None
        if save_debug:
            DEBUG_HTML.write_text(html, encoding="utf-8")
            print(f"    [debug] Saved rendered HTML to {DEBUG_HTML}")
        return BeautifulSoup(html, "lxml")
    except Exception as e:
        print(f"    X Error loading facId={fac_id}: {e}")
        return None


# ── Photo ─────────────────────────────────────────────────────────────────────

def get_photo_url(fac_id: str) -> str:
    """
    Return the HBS headshot API URL for this faculty member.
    The URL is predictable — no scraping required.
    """
    return HEADSHOT_BASE.format(fac_id)


# ── Profile detail scraping ───────────────────────────────────────────────────

def scrape_profile_details(soup) -> dict:
    """
    Extract bio, title, unit, and email from a fully-rendered HBS faculty profile page.

    Returns a dict with keys: title, bio, email, unit (each str or None).
    """
    title = _scrape_title(soup)
    bio   = _scrape_bio(soup)
    email = _scrape_email(soup)
    unit  = _scrape_unit(soup)
    return {"title": title, "bio": bio, "email": email, "unit": unit}


def _scrape_title(soup) -> str | None:
    """
    Faculty title/rank (e.g. "Baker Foundation Professor of Business Administration").
    HBS renders this in an <h2 class="... subtitle ..."> element in the profile header.
    """
    # Primary: h2 with class "subtitle" (confirmed from HBS profile HTML)
    for h2 in soup.find_all("h2", class_="subtitle"):
        text = h2.get_text(strip=True)
        if text and 3 < len(text) < 150:
            return text

    # Fallback: any h2/h3 whose text looks like a professorship
    TITLE_RE = re.compile(r'\bProfessor\b', re.I)
    for tag in soup.find_all(["h2", "h3"]):
        classes = " ".join(tag.get("class", []))
        if re.search(r"toggle|nav|menu|footer|breadcrumb", classes, re.I):
            continue
        text = tag.get_text(strip=True)
        if 5 < len(text) < 150 and TITLE_RE.search(text):
            return text

    return None


_PUB_ARTIFACT_PATTERNS = [
    re.compile(r"\bView Details\b"),
    re.compile(r"\bEds?\.\b"),
    re.compile(r"\bet al\b", re.I),
    re.compile(r"\bBooks\s+Books\b"),
    re.compile(r"\bJournal Articles\s+Journal Articles\b"),
]


def _is_publication_content(text: str) -> bool:
    """
    Return True if text looks like a publication/citation list rather than
    a biographical narrative. Uses multiple signals — a single weak match
    is not sufficient to reject.
    """
    hits = sum(1 for p in _PUB_ARTIFACT_PATTERNS if p.search(text))
    if hits >= 2:
        return True
    # Year density: more year citations than sentence-ending transitions → list
    year_count = len(re.findall(r"\b(19|20)\d{2}\b", text))
    sentence_count = len(re.findall(r"[.!?]\s+[A-Z]", text))
    if year_count > 5 and year_count > sentence_count:
        return True
    return False


def _scrape_bio(soup) -> str | None:
    """
    Faculty biography text.

    Candidate priority:
      1. HBS-specific class names (fullBio, fullbio, briefbio) — confirmed from
         real profile pages; these are the most reliable targets.
      2. Generic class patterns as fallback.
      3. Conservative div scan as last resort.

    All candidates are validated against _is_nav_content() and the new
    _is_publication_content() check so that citation lists (like Lakhani's
    book bibliography) are not mistaken for biographical narrative.
    """
    # ── HBS-specific selectors (priority order) ───────────────────────────────
    hbs_classes = ("fullBio", "fullbio", "briefbio")
    # ── Generic fallbacks ─────────────────────────────────────────────────────
    generic_candidates = [
        soup.find(class_=re.compile(r"biography|bio-text|faculty-bio", re.I)),
        soup.find("div", class_=re.compile(r"faculty.content|profile.content", re.I)),
        soup.find("section", class_=re.compile(r"bio|about", re.I)),
    ]

    candidates = [soup.find(class_=cls) for cls in hbs_classes]
    candidates += generic_candidates

    for el in candidates:
        if not el:
            continue
        paras = el.find_all("p")
        if paras:
            text = " ".join(p.get_text(separator=" ", strip=True) for p in paras)
        else:
            text = el.get_text(separator=" ", strip=True)
        if (
            text
            and len(text) >= 80
            and not _is_nav_content(text)
            and not _is_publication_content(text)
        ):
            return _clean_bio(text)

    # ── Conservative div fallback ─────────────────────────────────────────────
    pub_containers = soup.find_all("div", class_="toggle-container")
    pub_texts = {c.get_text()[:50] for c in pub_containers}

    for div in soup.find_all("div"):
        classes = " ".join(div.get("class", []))
        if re.search(r"nav|menu|footer|header|sidebar|toggle|breadcrumb", classes, re.I):
            continue
        text = div.get_text(separator=" ", strip=True)
        if text[:50] in pub_texts:
            continue
        if 200 <= len(text) <= 3000:
            if (
                re.search(r"[.!?]\s", text)
                and not _is_nav_content(text)
                and not _is_publication_content(text)
            ):
                return _clean_bio(text)

    return None


# Fingerprint phrases that appear in HBS page navigation/chrome but never in real bios.
# Two or more hits → the text is scraped page furniture, not a biographical paragraph.
_HBS_NAV_PHRASES = [
    "Faculty & Research",
    "Baker Library",
    "Harvard Business Review",
    "Academic Programs",
    "Map & Directions",
    "Soldiers Field",
    "Site Map",
    "Recruit",
]

def _is_nav_content(text: str) -> bool:
    """Return True if the text looks like scraped navigation rather than a real bio."""
    hits = sum(1 for phrase in _HBS_NAV_PHRASES if phrase in text)
    return hits >= 2


def _clean_bio(text: str) -> str:
    """Strip scraping artifacts (e.g. 'Read more' buttons) from bio text."""
    # Remove "Read more" and anything after it (HBS website expand-button text)
    text = re.sub(r"\s*\bRead more\b.*$", "", text, flags=re.I | re.DOTALL)
    return text.strip()[:4000]


CANONICAL_UNITS = [
    "Accounting & Management",
    "Business, Government & International Economy",
    "Entrepreneurial Management",
    "Finance",
    "General Management",
    "Marketing",
    "Negotiation, Organizations & Markets",
    "Organizational Behavior",
    "Strategy",
    "Technology & Operations Management",
]


def _normalize_unit_name(text: str) -> str:
    """Lowercase, collapse whitespace, treat '&' and 'and' as equivalent."""
    text = text.strip().lower()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\band\b", "&", text)
    return text


_NORMALIZED_CANONICAL: dict[str, str] = {
    _normalize_unit_name(u): u for u in CANONICAL_UNITS
}


def _match_canonical_unit(text: str) -> str | None:
    """Return canonical unit name if text matches (with & / 'and' equivalence), else None."""
    return _NORMALIZED_CANONICAL.get(_normalize_unit_name(text))


def _scrape_unit(soup) -> str | None:
    """
    Extract the faculty member's academic unit from their profile page.

    Primary: <a> tags whose href contains /faculty/units/ — these appear only
    in the profile sidebar/breadcrumb unit designation, not in global navigation.
    Collects all distinct canonical matches; returns None when ambiguous (multiple
    found) rather than silently guessing.

    Fallback: explicit "<Unit Name> Unit" pattern in bio text, used only when
    structural link extraction is inconclusive.

    Deliberately avoids full-page soup.get_text() scans and generic all-anchor
    scans — those were the root cause of Finance/Marketing misclassifications
    caused by site-wide navigation links.
    """
    # ── Primary: /faculty/units/ href links ───────────────────────────────────
    # Links containing /faculty/units/ are uniquely associated with the unit
    # designation area on HBS profile pages and never appear in global nav.
    unit_matches: set[str] = set()
    for a in soup.find_all("a", href=re.compile(r"/faculty/units/", re.I)):
        matched = _match_canonical_unit(a.get_text(strip=True))
        if matched:
            unit_matches.add(matched)

    if len(unit_matches) == 1:
        return next(iter(unit_matches))
    # Multiple distinct units found — do not guess; fall through to bio inspection.

    # ── Fallback: explicit unit statement in bio text ─────────────────────────
    # Bio text often contains phrasing like "in the Technology and Operations
    # Management Unit at HBS". Only use this when structural extraction fails.
    for bio_class in ("fullBio", "fullbio", "briefbio"):
        bio_el = soup.find(class_=bio_class)
        if not bio_el:
            continue
        bio_text = bio_el.get_text(separator=" ", strip=True)
        for unit in CANONICAL_UNITS:
            alt = unit.replace(" & ", " and ")
            pattern = re.compile(
                r"(?:" + re.escape(unit) + r"|" + re.escape(alt) + r").{0,40}Unit\b",
                re.I,
            )
            if pattern.search(bio_text):
                return unit

    return None


def _scrape_email(soup) -> str | None:
    """Extract first mailto: link from the page."""
    a = soup.find("a", href=re.compile(r"^mailto:", re.I))
    if a:
        href = a.get("href", "")
        email = href[len("mailto:"):].split("?")[0].strip()
        if "@" in email:
            return email
    return None



# ── Publication scraping ──────────────────────────────────────────────────────

def scrape_publications(soup, fac_id: str) -> list:
    """
    Extract recent publications from a fully-rendered HBS faculty profile page.

    HBS page structure:
      <div class="toggle-container">
        <h3 class="eta-uc">
          <div class="toggle-hide"><a>JOURNAL ARTICLES</a></div>
        </h3>
        <div class="toggle-hide has-slide">
          <ul class="unstyled list-publications ...">
            <li><div>Authors. <a href="...">Title</a> Journal Year. <a>View Details</a></div></li>
            ...
          </ul>
        </div>
      </div>
    """
    pubs = []

    for container in soup.find_all("div", class_="toggle-container"):
        h3 = container.find("h3")
        if not h3:
            continue

        heading_text = h3.get_text(strip=True).lower()
        # Normalise plural: "journal articles" -> match "journal article"
        heading_text = heading_text.rstrip("s")

        pub_type = None
        for pattern, ptype in PUB_SECTION_TYPES.items():
            if pattern in heading_text:
                pub_type = ptype
                break
        if pub_type is None:
            continue

        pub_list = container.find("ul", class_=re.compile(r"list-publication", re.I))
        if not pub_list:
            # Fallback: any ul within the container
            pub_list = container.find("ul")
        if not pub_list:
            continue

        for li in pub_list.find_all("li", recursive=False):
            pub = _parse_pub_entry(li, pub_type)
            if pub:
                pubs.append(pub)

    pubs = _dedup_pubs(pubs)
    return _select_with_quotas(pubs)


def _select_with_quotas(pubs: list) -> list:
    """
    Select up to MAX_PUBLICATIONS publications using a quota-then-fill strategy:
      1. Guarantee up to TYPE_QUOTAS[type] most-recent pubs per priority type.
      2. Fill any remaining slots (up to MAX_PUBLICATIONS) with the most recent
         publications across all types not yet included.
      3. Return sorted by year descending.
    """
    # Sort all pubs by year desc once
    by_year = sorted(pubs, key=lambda p: p.get("year") or 0, reverse=True)

    selected = []
    seen = set()  # keyed by lowercased title prefix

    def _add(pub):
        key = pub["title"].lower()[:80]
        if key not in seen:
            seen.add(key)
            selected.append(pub)

    # Step 1 — fill guaranteed slots per priority type (most recent first)
    by_type = {}
    for pub in by_year:
        by_type.setdefault(pub["pub_type"], []).append(pub)

    for pub_type, quota in TYPE_QUOTAS.items():
        for pub in by_type.get(pub_type, [])[:quota]:
            _add(pub)

    # Step 2 — fill remaining slots with most-recent across all types
    for pub in by_year:
        if len(selected) >= MAX_PUBLICATIONS:
            break
        _add(pub)

    # Step 3 — return sorted by year desc
    selected.sort(key=lambda p: p.get("year") or 0, reverse=True)
    return selected


def _parse_pub_entry(entry, pub_type: str):
    """
    Parse a single <li> publication entry.

    HBS entry structure:
      <li>
        <div>Authors. <a href="URL">Title text <span class="pdf-append">(pdf)</span></a>
             <i>Journal Name</i> Vol (Year): pages. <a>View Details</a></div>
        <div class="shim20"></div>
      </li>
    """
    text = entry.get_text(separator=" ", strip=True)
    if len(text) < 10:
        return None

    # Find the first <a> that is NOT a "View Details" / toggle link
    title_tag = None
    url = None
    view_details_url = None
    for a in entry.find_all("a"):
        a_text = a.get_text(strip=True)
        href = a.get("href", "")
        if a_text.lower() in ("view details", "view detail", "") or href.startswith("#"):
            # Capture View Details URL as fallback for case entries
            if a_text.lower().startswith("view detail") and href and not href.startswith("#"):
                view_details_url = href if href.startswith("http") else "https://www.hbs.edu" + href
            continue
        title_tag = a
        if href and not href.startswith("#"):
            url = href if href.startswith("http") else "https://www.hbs.edu" + href
        break
    # Use View Details URL when there's no primary link (common for cases)
    if not url and view_details_url:
        url = view_details_url

    if title_tag:
        # Get title text, strip surrounding quotes and the "(pdf)" suffix
        raw_title = title_tag.get_text(strip=True)
        raw_title = re.sub(r"\s*\(pdf\)\s*$", "", raw_title, flags=re.I).strip()
        title = raw_title.strip('"').strip("\u201c\u201d").strip("'").strip()
    else:
        # No title link — title is in the plain text, usually in quotes.
        # e.g. 'Smith, J. "Case Title." HBS Case 123-456, 2024. View Details'
        quoted = re.search(r'["\u201c\u201e]([^"\u201c\u201d\u201e]{10,})["\u201d]', text)
        if quoted:
            title = quoted.group(1).strip().rstrip(".")
        else:
            # Last resort: use the italicised text if present
            italic = entry.find("i")
            title = italic.get_text(strip=True) if italic else ""

    if not title or len(title) < 5:
        return None

    # Year: first 4-digit year in the full text
    year_match = YEAR_RE.search(text)
    year = int(year_match.group()) if year_match else None

    # Journal: look for <i> tag (HBS italicises journal names)
    journal = None
    italic = entry.find("i")
    if italic:
        journal_text = italic.get_text(strip=True)
        if journal_text and len(journal_text) < 120:
            journal = journal_text

    return {"title": title, "year": year, "pub_type": pub_type, "journal": journal, "url": url}


def _dedup_pubs(pubs: list) -> list:
    seen = set()
    result = []
    for pub in pubs:
        key = pub["title"].lower()[:80]
        if key not in seen:
            seen.add(key)
            result.append(pub)
    return result


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    faculty_list = load_faculty()

    if FILTER_IDS:
        faculty_list = [(fid, name) for fid, name in faculty_list if fid in FILTER_IDS]
        output_file = Path(__file__).parent / "enriched_faculty_targeted.json"
    else:
        output_file = OUTPUT_FILE
        if START_FROM:
            faculty_list = faculty_list[START_FROM:]

    print("HBS Faculty Enrichment Scraper (Playwright)")
    print("=" * 50)
    print(f"Scraping {len(faculty_list)} faculty members"
          + (f" (starting from #{START_FROM + 1})" if START_FROM else "") + "...\n")

    results = []

    with sync_playwright() as pw:
        if _HAS_STEALTH:
            print(f"  playwright-stealth {_STEALTH.__class__.__module__} active")
        else:
            print("  playwright-stealth not found — running without it")
        print(f"  headless={HEADLESS}\n")

        browser = pw.chromium.launch(
            headless=HEADLESS,
            args=["--disable-blink-features=AutomationControlled"],
        )

        CONTEXT_RESTART_EVERY = 4  # fresh context every N faculty; smaller = harder to fingerprint

        def make_context():
            ctx = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/124.0.0.0 Safari/537.36"
                ),
                locale="en-US",
                timezone_id="America/New_York",
                viewport={"width": 1280, "height": 800},
            )
            # Mask common automation fingerprints
            ctx.add_init_script("""
                Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
                Object.defineProperty(navigator, 'plugins', {get: () => [1,2,3,4,5]});
                Object.defineProperty(navigator, 'languages', {get: () => ['en-US','en']});
                window.chrome = {runtime: {}};
            """)
            return ctx

        context = make_context()

        for i, (fac_id, name) in enumerate(faculty_list, 1):
            # Restart context periodically to clear memory and refresh connection
            if i > 1 and (i - 1) % CONTEXT_RESTART_EVERY == 0:
                context.close()
                pause = random.uniform(8, 15)
                print(f"\n  [restarting browser context after {i - 1} faculty — pausing {pause:.1f}s]\n")
                time.sleep(pause)
                context = make_context()

            print(f"[{i:3}/{len(faculty_list)}] {name} (facId={fac_id})")

            page = context.new_page()
            if _HAS_STEALTH:
                _STEALTH.apply_stealth_sync(page)
            soup = fetch_profile(page, fac_id, save_debug=(DEBUG and i == 1))
            page.close()

            photo_url    = get_photo_url(fac_id)
            publications = scrape_publications(soup, fac_id) if soup else []
            details      = scrape_profile_details(soup) if soup else {}

            type_counts = {}
            for p in publications:
                type_counts[p["pub_type"]] = type_counts.get(p["pub_type"], 0) + 1
            breakdown = ", ".join(f"{v} {k}" for k, v in sorted(type_counts.items()))
            has_bio   = "✓" if details.get("bio") else "–"
            has_email = "✓" if details.get("email") else "–"
            has_title = "✓" if details.get("title") else "–"
            has_unit  = "✓" if details.get("unit") else "–"
            print(f"           pubs: {len(publications)} ({breakdown})")
            print(f"           bio:{has_bio}  email:{has_email}  title:{has_title}  unit:{has_unit}")

            results.append({
                "hbs_fac_id":   fac_id,
                "photo_url":    photo_url,
                "title":        details.get("title"),
                "bio":          details.get("bio"),
                "email":        details.get("email"),
                "unit":         details.get("unit"),
                "tags":         [],   # managed via curated migration seed
                "publications": publications,
            })

            time.sleep(random.uniform(5, 12))  # randomised delay to avoid bot detection

        context.close()
        browser.close()

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    total_pubs   = sum(len(r["publications"]) for r in results)
    total_photos = sum(1 for r in results if r.get("photo_url"))
    total_bios   = sum(1 for r in results if r.get("bio"))
    total_emails = sum(1 for r in results if r.get("email"))
    total_titles = sum(1 for r in results if r.get("title"))
    total_units  = sum(1 for r in results if r.get("unit"))

    print("\n" + "=" * 50)
    print("Done!")
    print(f"   Photos (URL):         {total_photos}")
    print(f"   Bios scraped:         {total_bios}")
    print(f"   Titles scraped:       {total_titles}")
    print(f"   Units scraped:        {total_units}")
    print(f"   Emails scraped:       {total_emails}")
    print(f"   Publications scraped: {total_pubs}")
    print(f"   Output: {output_file}")
    print()
    if FILTER_IDS:
        print("Next step: node scripts/import-targeted-bios.mjs")
    else:
        print("Next step: node scripts/import-enriched.mjs")


if __name__ == "__main__":
    main()
