-- Pilot seed: 20 faculty members across 9 HBS units
-- Sourced from hbs.edu via the hbs-database scraper (github.com/nbtcub11/hbs-database)
-- Deduplicated by facId; names and emails cleaned of artifacts.

insert into faculty (hbs_fac_id, name, title, unit, email, bio, profile_url, image_url) values

-- ── Accounting & Management ───────────────────────────────────────────────────
('1324810',
 'Jung Koo Kang',
 'Assistant Professor of Business Administration',
 'Accounting & Management',
 'jung_kang@hbs.edu',
 'Jung Koo Kang is an Assistant Professor of Business Administration in the Accounting and Management Unit at Harvard Business School. His research focuses on financial technology and innovation, alternative data, debt contracting, and financial intermediation, examining how emerging technologies reshape credit markets.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=1324810',
 null),

('740159',
 'Jonas Heese',
 'Professor of Business Administration',
 'Accounting & Management',
 'jonas_heese@hbs.edu',
 'Jonas Heese is a Professor of Business Administration in the Accounting and Management Unit at Harvard Business School. His research focuses on corporate misconduct and the role of regulators, whistleblowers, the media, and compliance systems in preventing such misconduct.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=740159',
 null),

-- ── Business, Government & International Economy ──────────────────────────────
('1356397',
 'Jesse M. Shapiro',
 'George Gund Professor of Economics and Business Administration',
 'Business, Government & International Economy',
 'jesse_shapiro@hbs.edu',
 'Jesse Shapiro is the George Gund Professor of Economics and Business Administration at Harvard Business School. A 2021 MacArthur Fellow, his research on media bias, ideological polarization, and behavioral economics has been widely recognized, with The Economist naming him one of the 8 best young economists in the world.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=1356397',
 null),

('937841',
 'Caroline M. Elkins',
 'Thomas Henry Carroll/Ford Foundation Professor of Business Administration',
 'Business, Government & International Economy',
 'caroline_elkins@hbs.edu',
 'Caroline Elkins is the Thomas Henry Carroll/Ford Foundation Professor of Business Administration and founding director of Harvard''s Center for African Studies. Her book ''Imperial Reckoning: The Untold Story of Britain''s Gulag in Kenya'' was awarded the Pulitzer Prize for General Nonfiction.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=937841',
 null),

-- ── Entrepreneurial Management ────────────────────────────────────────────────
('6463',
 'Paul A. Gompers',
 'Eugene Holman Professor of Business Administration',
 'Entrepreneurial Management',
 'paul_gompers@hbs.edu',
 'Paul Gompers is the Eugene Holman Professor of Business Administration at Harvard Business School, specializing in venture capital, private equity, and entrepreneurial finance. He has co-authored three books on the venture capital industry and served as director of research at HBS for nine years.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6463',
 null),

('337264',
 'Tom Nicholas',
 'William J. Abernathy Professor of Business Administration',
 'Entrepreneurial Management',
 'tom_nicholas@hbs.edu',
 'Tom Nicholas is the William J. Abernathy Professor of Business Administration at Harvard Business School. His research focuses on the history of entrepreneurship, innovation, and finance, and he is the author of ''VC: An American History'' which examines the historical roots of the U.S. venture capital industry.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=337264',
 null),

-- ── Finance ───────────────────────────────────────────────────────────────────
('10639',
 'Malcolm Baker',
 'Robert G. Kirby Professor of Business Administration',
 'Finance',
 'malcolm_baker@hbs.edu',
 'Malcolm Baker is the Robert G. Kirby Professor of Business Administration at Harvard Business School. His research focuses on behavioral finance, corporate finance, and capital markets, particularly the interactions among corporate finance, investor behavior, and market inefficiency. He is also a former Olympic rower.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=10639',
 null),

('92011',
 'John D. Macomber',
 'Senior Lecturer',
 'Finance',
 'john_macomber@hbs.edu',
 'John Macomber is a Senior Lecturer in the Finance Unit and Faculty Chair of the HBS Africa Research Center at Harvard Business School. His work focuses on climate adaptation and infrastructure finance, particularly public-private partnerships for delivering resilient infrastructure in developing and emerging markets.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=92011',
 null),

-- ── Marketing ─────────────────────────────────────────────────────────────────
('244024',
 'Anita Elberse',
 'Lincoln Filene Professor of Business Administration',
 'Marketing',
 'anita_elberse@hbs.edu',
 'Anita Elberse is the Lincoln Filene Professor of Business Administration at Harvard Business School. One of the youngest women to earn tenure at HBS, she specializes in entertainment, media, and sports industries, and authored ''Blockbusters: Hit-making, Risk-taking, and the Big Business of Entertainment.''',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=244024',
 null),

('261323',
 'Sunil Gupta',
 'Edward W. Carter Professor of Business Administration',
 'Marketing',
 'sunil_gupta@hbs.edu',
 'Sunil Gupta is the Edward W. Carter Professor of Business Administration at Harvard Business School. His research focuses on digital technology''s impact on consumer behavior and firm strategy, and his book ''Driving Digital Strategy'' guides businesses through digital transformation.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=261323',
 null),

-- ── Negotiation, Organizations & Markets ─────────────────────────────────────
('1495303',
 'Alex Chan',
 'Assistant Professor',
 'Negotiation, Organizations & Markets',
 'alex_chan@hbs.edu',
 'Alex Chan is an Assistant Professor at Harvard Business School who studies how market failures occur and how to design incentives and engineer markets to remedy them. A former McKinsey consultant and Optum executive, he has worked with healthcare organizations to launch actual marketplaces including a liver exchange in Pakistan.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=1495303',
 null),

('326229',
 'Michael I. Norton',
 'Harold M. Brierley Professor of Business Administration',
 'Negotiation, Organizations & Markets',
 'michael_norton@hbs.edu',
 'Michael Norton is the Harold M. Brierley Professor of Business Administration at Harvard Business School. His research on behavioral economics and well-being led to the bestselling book ''Happy Money: The Science of Happier Spending,'' and his TEDx talk on buying happiness has over 4.5 million views.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=326229',
 null),

-- ── Organizational Behavior ───────────────────────────────────────────────────
('6479',
 'Linda A. Hill',
 'Wallace Brett Donham Professor of Business Administration',
 'Organizational Behavior',
 'linda_hill@hbs.edu',
 'Linda Hill is the Wallace Brett Donham Professor of Business Administration and Faculty Chair of the Leadership Initiative at Harvard Business School. She is co-author of ''Collective Genius: The Art and Practice of Leading Innovation'' and her TED talk on managing for creativity has over 2.6 million views.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6479',
 null),

('10650',
 'Boris Groysberg',
 'Richard P. Chapman Professor of Business Administration',
 'Organizational Behavior',
 'boris_groysberg@hbs.edu',
 'Boris Groysberg is the Richard P. Chapman Professor of Business Administration at Harvard Business School. His research focuses on talent management and how firms can achieve sustainable competitive advantage through human capital, and he authored ''Chasing Stars: The Myth of Talent and the Portability of Performance.''',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=10650',
 null),

-- ── Strategy ──────────────────────────────────────────────────────────────────
('24279',
 'Ramon Casadesus-Masanell',
 'Herman C. Krannert Professor of Business Administration',
 'Strategy',
 'ramon_casadesus-masanell@hbs.edu',
 'Ramon Casadesus-Masanell is the Herman C. Krannert Professor of Business Administration at Harvard Business School. He studies strategic interaction between organizations with different business models and co-edits the Journal of Economics and Management Strategy.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=24279',
 null),

('871877',
 'Andy Wu',
 'Arjun and Minoo Melwani Family Associate Professor of Business Administration',
 'Strategy',
 'andy_wu@hbs.edu',
 'Andy Wu is the Arjun and Minoo Melwani Family Associate Professor at Harvard Business School. His research examines how technology entrepreneurs organize resources and adapt to cutting-edge technologies like generative AI and digital platforms, and he has received the HBS Wyss Award and Poets & Quants 40 Under 40 recognition.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=871877',
 null),

-- ── Technology & Operations Management ───────────────────────────────────────
('6482',
 'Marco Iansiti',
 'David Sarnoff Professor of Business Administration',
 'Technology & Operations Management',
 'marco_iansiti@hbs.edu',
 'Marco Iansiti is the David Sarnoff Professor of Business Administration at Harvard Business School and co-director of the Laboratory for Information Science at Harvard. His research examines digital transformation and AI''s impact on strategy, and he co-authored the bestselling ''Competing in the Age of AI.''',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6482',
 null),

('6451',
 'Amy C. Edmondson',
 'Novartis Professor of Leadership and Management',
 'Technology & Operations Management',
 'amy_edmondson@hbs.edu',
 'Amy Edmondson is the Novartis Professor of Leadership and Management at Harvard Business School. She coined the term ''team psychological safety'' and is ranked #1 on Thinkers50''s global ranking of management thinkers. Her book ''The Fearless Organization'' has become a foundational text on workplace culture.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6451',
 null),

('240491',
 'Karim R. Lakhani',
 'Dorothy & Michael Hintze Professor of Business Administration',
 'Technology & Operations Management',
 'klakhani@hbs.edu',
 'Karim R. Lakhani is the Dorothy & Michael Hintze Professor of Business Administration at Harvard Business School and co-founder and chair of the Digital, Data & Design Institute at Harvard. His research focuses on technology management, innovation, digital transformation, and artificial intelligence, and he directs the Laboratory for Innovation Science at Harvard.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=240491',
 'https://d3.harvard.edu/wp-content/uploads/2025/09/K.LakhaniHeadShot.jpg'),

('14938',
 'Feng Zhu',
 'MBA Class of 1958 Professor of Business Administration',
 'Technology & Operations Management',
 'feng_zhu@hbs.edu',
 'Feng Zhu is the MBA Class of 1958 Professor of Business Administration at Harvard Business School, where he leads the Platform Lab. His research focuses on platform strategy, digital transformation, and business model innovation, and he has advised firms including Alphabet, Meta, Microsoft, and Uber.',
 'https://www.hbs.edu/faculty/Pages/profile.aspx?facId=14938',
 null)

on conflict (hbs_fac_id) do nothing;
