-- Batch 3: correct/fill faculty emails for rows 201–276
-- Format: [first_initial][last_name]@hbs.edu

-- Fix underscore-format entries
update faculty set email = 'rlal@hbs.edu'          where name = 'Rajiv Lal';
update faculty set email = 'rkhurana@hbs.edu'       where name = 'Rakesh Khurana';
update faculty set email = 'rgulati@hbs.edu'        where name = 'Ranjay Gulati';
update faculty set email = 'rruback@hbs.edu'        where name = 'Richard S. Ruback';
update faculty set email = 'rsimons@hbs.edu'        where name = 'Robert Simons';
update faculty set email = 'rbuell@hbs.edu'         where name = 'Ryan W. Buell';
update faculty set email = 'szhang@hbs.edu'         where name = 'Shunyuan Zhang';
update faculty set email = 'ssrinivasan@hbs.edu'    where name = 'Suraj Srinivasan';
update faculty set email = 'sgallani@hbs.edu'       where name = 'Susanna Gallani';
update faculty set email = 'vpons@hbs.edu'          where name = 'Vincent Pons';

-- Fill null entries
update faculty set email = 'rcohen@hbs.edu'         where name = 'Randolph B. Cohen';
update faculty set email = 'rkluender@hbs.edu'      where name = 'Ray Kluender';
update faculty set email = 'rkarp@hbs.edu'          where name = 'Rebecca A. Karp';
update faculty set email = 'rhenderson@hbs.edu'     where name = 'Rebecca M. Henderson';
update faculty set email = 'rherzlinger@hbs.edu'    where name = 'Regina E. Herzlinger';
update faculty set email = 'rkoning@hbs.edu'        where name = 'Rembrand M. Koning';
update faculty set email = 'rgaineddenova@hbs.edu'  where name = 'Renata Gaineddenova';
update faculty set email = 'rhussam@hbs.edu'        where name = 'Reshmaan N. Hussam';
update faculty set email = 'rsatchu@hbs.edu'        where name = 'Reza R. Satchu';
update faculty set email = 'rmarkey@hbs.edu'        where name = 'Rob Markey';
update faculty set email = 'rwhite@hbs.edu'         where name = 'Robert F. White';
update faculty set email = 'rgreenwood@hbs.edu'     where name = 'Robin Greenwood';
update faculty set email = 'rely@hbs.edu'           where name = 'Robin J. Ely';
update faculty set email = 'rdeshpande@hbs.edu'     where name = 'Rohit Deshpande';
update faculty set email = 'rkanter@hbs.edu'        where name = 'Rosabeth M. Kanter';
update faculty set email = 'ryudkoff@hbs.edu'       where name = 'Royce G. Yudkoff';
update faculty set email = 'rraffaelli@hbs.edu'     where name = 'Ryan L. Raffaelli';
update faculty set email = 'showell@hbs.edu'        where name = 'Sabrina T. Howell';
update faculty set email = 'santill@hbs.edu'        where name = 'Samuel B. Antill';
update faculty set email = 'shanson@hbs.edu'        where name = 'Samuel G. Hanson';
update faculty set email = 'ssucher@hbs.edu'        where name = 'Sandra J. Sucher';
update faculty set email = 'sfleiss@hbs.edu'        where name = 'Sara L. Fleiss';
update faculty set email = 'storti@hbs.edu'         where name = 'Sara McKinley Torti';
update faculty set email = 'stadikonda@hbs.edu'     where name = 'Satish K. Tadikonda';
update faculty set email = 'skominers@hbs.edu'      where name = 'Scott Duke Kominers';
update faculty set email = 'shillenbrand@hbs.edu'   where name = 'Sebastian Hillenbrand';
update faculty set email = 'sbernstein@hbs.edu'     where name = 'Shai Benjamin Bernstein';
update faculty set email = 'sgreenstein@hbs.edu'    where name = 'Shane M. Greenstein';
update faculty set email = 'scole@hbs.edu'          where name = 'Shawn A. Cole';
update faculty set email = 'sghosh@hbs.edu'         where name = 'Shikhar Ghosh';
update faculty set email = 'slu@hbs.edu'            where name = 'Shirley Lu';
update faculty set email = 'sreinert@hbs.edu'       where name = 'Sophus A. Reinert';
update faculty set email = 'sdatar@hbs.edu'         where name = 'Srikant M. Datar';
update faculty set email = 'sthomke@hbs.edu'        where name = 'Stefan H. Thomke';
update faculty set email = 'sgilson@hbs.edu'        where name = 'Stuart C. Gilson';
update faculty set email = 'sjackson@hbs.edu'       where name = 'Summer R. Jackson';
update faculty set email = 'tkhanna@hbs.edu'        where name = 'Tarun Khanna';
update faculty set email = 'tsandino@hbs.edu'       where name = 'Tatiana Sandino';
update faculty set email = 'tjennings@hbs.edu'      where name = 'Thomas H. Jennings';
update faculty set email = 'tdelong@hbs.edu'        where name = 'Thomas J. DeLong';
update faculty set email = 'teisenmann@hbs.edu'     where name = 'Thomas R. Eisenmann';
update faculty set email = 'tzhang@hbs.edu'         where name = 'Ting Zhang';
update faculty set email = 'tzuzul@hbs.edu'         where name = 'Tiona W. Zuzul';
update faculty set email = 'tlensman@hbs.edu'       where name = 'Todd Lensman';
update faculty set email = 'tclay@hbs.edu'          where name = 'Tom Clay';
update faculty set email = 'tamano@hbs.edu'         where name = 'Tomomichi Amano';
update faculty set email = 'tfetter@hbs.edu'        where name = 'Trevor Fetter';
update faculty set email = 'tneeley@hbs.edu'        where name = 'Tsedal Neeley';
update faculty set email = 'vrangan@hbs.edu'        where name = 'V. Kasturi Rangan';
update faculty set email = 'vnarayanan@hbs.edu'     where name = 'V.G. Narayanan';
update faculty set email = 'vivashina@hbs.edu'      where name = 'Victoria Ivashina';
update faculty set email = 'vgandhi@hbs.edu'        where name = 'Vikram Gandhi';
update faculty set email = 'wkester@hbs.edu'        where name = 'W. Carl Kester';
update faculty set email = 'wkelly@hbs.edu'         where name = 'W. Matt Kelly';
update faculty set email = 'wfriedman@hbs.edu'      where name = 'Walter A. Friedman';
update faculty set email = 'wdu@hbs.edu'            where name = 'Wenxin Du';
update faculty set email = 'wkirby@hbs.edu'         where name = 'William C. Kirby';
update faculty set email = 'wvrattos@hbs.edu'       where name = 'William C. Vrattos';
update faculty set email = 'wmarks@hbs.edu'         where name = 'William H. Marks';
update faculty set email = 'wkerr@hbs.edu'          where name = 'William R. Kerr';
update faculty set email = 'wemmons@hbs.edu'        where name = 'Willis M. Emmons';
update faculty set email = 'wshih@hbs.edu'          where name = 'Willy C. Shih';
update faculty set email = 'ymoon@hbs.edu'          where name = 'Youngme Moon';
update faculty set email = 'yzou@hbs.edu'           where name = 'Yuan Zou';
update faculty set email = 'yzhou@hbs.edu'          where name = 'Yue Maggie Zhou';
update faculty set email = 'zcullen@hbs.edu'        where name = 'Zoe B. Cullen';
